version: '3.7'

services:

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
    - 45323:16686/tcp
    volumes:
    - jaeger-volume:/tmp:rw

  mariadb:
    image: mariadb:latest
    ports:
    - 45322:3306/tcp
    environment:
    - MYSQL_RANDOM_ROOT_PASSWORD=yes
    - MYSQL_DATABASE=cineworld
    - MYSQL_USER=movietimes
    - MYSQL_PASSWORD_FILE=/run/secrets/Password
    volumes:
    - mariadb-volume:/var/lib/mysql:rw
    - ./MovieTimes.Db:/docker-entrypoint-initdb.d
    secrets:
    - source: Password
 
  service:
    image: eassbhhtgu/movietimes-service:latest
    environment:
    - NETCORE_ENVIRONMENT=Production
    depends_on:
    - jaeger
    - mariadb
    secrets:
    - source: Password
 
  api:
    image: eassbhhtgu/movietimes-api:latest
    environment:
    - ASPNETCORE_ENVIRONMENT=Production
    ports:
    - 45321:80/tcp
    depends_on:
    - jaeger
    - mariadb
    secrets:
    - source: Password

secrets:
  Password:
    external: true
    name: MySqlCineworldPassword

volumes:
  jaeger-volume: {}
  mariadb-volume: {}
