//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieTimes.CineworldService.Repositories.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MovieTimes.CineworldService.Repositories.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE `cineworld`.`cinema` (
        ///  `id` SMALLINT(2) UNSIGNED NOT NULL,
        ///  `name` VARCHAR(100) NOT NULL,
        ///  PRIMARY KEY (`id`),
        ///  UNIQUE INDEX `uix_cineworld_cinema` (`name`)
        ///);.
        /// </summary>
        internal static string cinema {
            get {
                return ResourceManager.GetString("cinema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE `cineworld`.`film` (
        ///  `edi` INT UNSIGNED NOT NULL,
        ///  `title` VARCHAR(100) NOT NULL,
        ///  PRIMARY KEY (`edi`),
        ///  UNIQUE INDEX `uix_cineworld_film` (`title`)
        ///);.
        /// </summary>
        internal static string film {
            get {
                return ResourceManager.GetString("film", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE `cineworld`.`show` (
        ///  `cinemaId` SMALLINT(2) UNSIGNED NOT NULL,
        ///  `filmEdi` INT UNSIGNED NOT NULL,
        ///  `time` DATETIME NOT NULL,
        ///  PRIMARY KEY (`cinemaId`, `filmEdi`, `time`),
        ///    FOREIGN KEY fk_cinemaId_film_edi(`cinemaId`)
        ///    REFERENCES `cineworld`.`cinema` (`id`)
        ///    ON DELETE CASCADE
        ///    ON UPDATE NO ACTION,
        ///    FOREIGN KEY fk_filmEdi_film_edi(`filmEdi`)
        ///    REFERENCES `cineworld`.`film` (`edi`)
        ///    ON DELETE CASCADE
        ///    ON UPDATE NO ACTION
        ///);.
        /// </summary>
        internal static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
    }
}
